version: '3.9'

services:
  crud-nestjs:
    platform: linux/x86_64
    container_name: crud-nestjs
    build:
      context: ./
      target: "stage"
      # target: "development"
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
      - "9229:9229"
    depends_on:
      - postgres
      - redis
    networks: 
      - local    

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./temp/postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - local
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - postgres
    networks:
      - local

  redis:
    container_name: redis
    image: redis:7.2.4
    ports:
      - "6379:6379"
    volumes:
      -  ./temp/redis:/data
    networks:
      - local

  redisinsight:
    container_name: redisinsight
    image: redislabs/redisinsight:1.14.0
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - ./temp/redisinsight:/db 
    networks:
      - local
      
networks: 
  local:
    name: local